name: safe_sight
description: Campus safety app with Life360-like features

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.2
  cupertino_icons: ^1.0.6
  geolocator: ^12.0.0
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  fluttertoast: ^8.2.6
  vibration: ^3.1.3
  intl: ^0.19.0
  google_maps_flutter: ^2.5.3
  flutter_dotenv: ^5.1.0
  http: ^1.1.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  uuid: ^4.3.3
  video_player: ^2.8.2
  video_thumbnail: ^0.5.3
  path: ^1.8.3
  audioplayers: ^5.2.1
  camera: ^0.10.5+9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true